### ISSUE TITLE
Error to install

### ISSUE THREAD

**Issue by edersign** [trustworktech/create-react-ssr-app#1]
Hi, i'm try install, and receive this error.

`[eval]:3
        init.apply(null, JSON.parse(process.argv[1]));
             ^

TypeError: init.apply is not a function
    at [eval]:3:14
    at Script.runInThisContext (vm.js:123:20)
    at Object.runInThisContext (vm.js:312:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at evalScript (internal/process/execution.js:56:25)
    at executeUserCode (internal/bootstrap/node.js:499:5)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)

Aborting installation.
  node  has failed.`

**Comment by maxparelius** [comment]
Hi @edersign thanks for your interest in the project! This is actually a work in progress we plan to have it available in the next week or two. I will let you know as soon as it is ready to use!

**Comment by edersign** [comment]
thank you @maxparelius , I will wait!

**Comment by Butonix** [comment]
Have you fixed this error yet?

> Hi @edersign thanks for your interest in the project! This is actually a work in progress we plan to have it available in the next week or two. I will let you know as soon as it is ready to use!

Have you fixed this error yet?

**Comment by maxparelius** [comment]
@Butonix @edersign the current state of the project is that we have the following working:
 - initialization script `npx create-react-ssr-app my-app`
 - test script `react-ssr-scripts test`
 - build script `react-ssr-scripts build`

Just need to finish up the start script: `react-ssr-scripts start` and then will be ready to use! Should have that done in a couple days. Then will work on the eject script but hopefully that is not needed!

Thanks.

**Comment by Butonix** [comment]
> * npx create-react-ssr-app my-app
It deletes all files.

[eval]:3
        init.apply(null, JSON.parse(process.argv[1]));
             ^

TypeError: init.apply is not a function
    at [eval]:3:14
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:653:30)
    at evalScript (bootstrap_node.js:479:27)
    at startup (bootstrap_node.js:180:9)
    at bootstrap_node.js:625:3

Aborting installation.
  node  has failed.

Deleting generated file... node_modules
Deleting generated file... package.json
Deleting generated file... yarn.lock

**Comment by maxparelius** [comment]
@Butonix @edersign Should be good to go now: `npx create-react-ssr-app my-app`. Let me know if any issues. More detailed documentation on how to use the setup coming soon.

**Comment by Butonix** [comment]
> @Butonix @edersign Should be good to go now: `npx create-react-ssr-app my-app`. Let me know if any issues. More detailed documentation on how to use the setup coming soon.

OK. Everything is working.
The only thing you need to try to make an example with redux
since now i am getting an error
Invariant Violation: Could not find "store" in either the context or props of "Connect(App)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(App)".

**Comment by maxparelius** [comment]
@Butonix yep goal of the project is to not add things like redux or react-router to keep it unopinionated but going to be rolling out documentation soon giving examples of how to integrate react-router, redux, etc.

**Comment by maxparelius** [comment]
@Butonix going to close this now since the original issue is solved. Will reach out when the documentation to add react router and redux is up.

**Comment by maxparelius** [comment]
@Butonix documentation site is up. Sections on react router and redux included. You can look here: https://trustworktech.github.io/create-react-ssr-app/docs/adding-react-router

**Comment by Butonix** [comment]
> @Butonix documentation site is up. Sections on react router and redux included. You can look here: https://trustworktech.github.io/create-react-ssr-app/docs/adding-react-router

@maxparelius I redid my project as you have written in the documentation, and constantly get an error
`TypeError: Cannot read property 'pathname' of undefined`
with create-react-app there was no such mistake.
What could be the problem?
I have a switch in my

**navbar**
```
const dropdownLinks =
      this.props.location.pathname !== "/" &&
      this.props.location.pathname !== "/new"
        ? this.state.links.filter(el => el.pathname !== this.state.currentLink)
        : this.state.links.filter(el => el.pathname !== "/");
```

**in App.js**
```
App.propTypes = {
  location: PropTypes.shape({
    pathname: PropTypes.string.isRequired
  }).isRequired
};
```

**client.js**
```
ReactDOM.hydrate(
    <ReduxProvider store={store}>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </ReduxProvider>,
  document.getElementById("root")
);
```

**App.js**
```
const App = ({ location }) => (
<Switch>
  <Route
    location={location}
    exact
    path="/"
    render={() => (<MainArticlesPage/>)}
/>
</Switch>
)
```

**render.js**
```
<ReduxProvider store={store}>
    <StaticRouter location={req.url} context={routerContext}>
      <App />
    </StaticRouter>
</ReduxProvider>
```

P.S. YOU HAVE EXCESSABLE BRACKET
```
const htmlReplacements = {
      HTML_CONTENT: htmlContent,
+     PRELOADED_STATE: serialize(store.getState(), {
+       isJSON: true,
+     })}, <------YOU HAVE EXCESSABLE BRACKET
    };
```

**Comment by maxparelius** [comment]
@Butonix thanks for the flag of the typo on the docs, it's been updated. As for your error. Hard for me to tell exactly what is going on but keep in mind now that you are doing server-side rendering you have to be careful since your code is rendering twice (1 time on the server and 1 time in the client) for initial render. My guess is that you are passing undefined `location` object in `App.js`. Trying adding
```
import { withRouter } from 'react-router-dom';
```
to the top of the file and then wrapping your `App` when you export like this:
```
export default `withRouter(App)`
```
to ensure `location` is defined on server and client.

**Comment by maxparelius** [comment]
@Butonix or you could just not pass `location` explicitly to the `Route` component like you are doing. React Router does this for you already and will ensure it gets passed correctly.

**Comment by Butonix** [comment]
> @Butonix or you could just not pass `location` explicitly to the `Route` component like you are doing. React Router does this for you already and will ensure it gets passed correctly.

@maxparelius Thank. Now earned!
But after launch, the application runs on port 8000
and it requires files from port 8080
but accordingly he does not find them
<script src="http://0.0.0.0:8080/static/js/bundle.js">
It works only this way, but where can I change it so that during assembly it uses this dam during 
development, and during production?
<script src="http://localhost:8080/static/js/bundle.js">

**Comment by maxparelius** [comment]
@Butonix try updating `react-ssr-scripts` I submitted a fix for this. In development it should point to the webpack dev server on port 8080 but in production it should load the js scripts from the node app itself on port 8000.

**Comment by Butonix** [comment]
> @Butonix try updating `react-ssr-scripts` I submitted a fix for this. In development it should point to the webpack dev server on port 8080 but in production it should load the js scripts from the node app itself on port 8000.

Hello @maxparelius!
Tell me how to add a proxy to the webpack? api to work
I get errors
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
ReferenceError: document is not defined
`http://localhost:3000/__get-internal-source?fileName=webpack-internal%3A%2F%2F%2F.%2Fnode_modules%2Faxios%2Flib%2Fadapters%2Fxhr.js`
