### ISSUE TITLE
How to write your own api breakpoints?

### ISSUE THREAD

**Issue by freestyle099** [trustworktech/create-react-ssr-app#11]
Hi!

I really enjoy your repo but I cannot find any information about creating your own API breakpoints.
Can you tell me how to write this:

app.get('/contact', (req,res) => { 
    res.send({id:1, name: 'test'});
}

and fetch this data from any components??

componentDidMount() {
   fetch('/contact').then(resp => resp.json()).then(data => console.log(data));
}

I'm getting error and this breakpoint it's not working.

Please answer me beacuse of that I cannot use your app well ;/

**Comment by freestyle099** [comment]
Ok i figured out :)

You can add in some documentation about fetching DATA or creating your own API breakpoints that you need to create them before html middleware. After it there is no next() method calling and none code will work.

**Comment by maxparelius** [comment]
@freestyle09 yes you are correct glad you figured things out.
