### ISSUE TITLE
Styles don't load in development (JS Disabled)

### ISSUE THREAD

**Issue by amitava82** [trustworktech/create-react-ssr-app#13]
Thanks for this awesome script, works perfect without any configs (after spending few hours with Razzle and scss). 👍 

Looks like the styles are not loaded in development if Javascript is disabled. Though it works fine in production version. Wanted to test pages with SSR in development with Js turned off. Is there any way to make the css load as well? Not a deal breaker though.

**Comment by maxparelius** [comment]
@amitava82 thanks for the support! I will have to look into that. The reason it doesnt work is becuase css is distributed by the webpack dev server which requires js, I can look into setting an env var that will allow you to bypass the webpack dev server for css. Will follow up.

**Comment by j-stuckey** [comment]
Is there any progress on the issue? I've recently taken an interest in SSR and found the project useful for using CRA and SSR at the same time. I would like to contribute to the project if I can.

**Comment by maxparelius** [comment]
@j-stuckey sorry for delay I am currently working on a rehaul of this project, will address this issue, and yes would be happy to have your contributions, what areas are you interested in helping? Documentation, core internals, bug fixes?

**Comment by j-stuckey** [comment]
I would be interested to help on core internals and bug fixes as well. I don't have much experience writing documentation but I can always be a second pair of eyes there as well.

**Comment by maxparelius** [comment]
@j-stuckey sounds great I am getting a roadmap of sorts in order so give me a couple days to finalize that and then we can discuss where you can help out. Thanks!
