### ISSUE TITLE
Customizing webpack config?

### ISSUE THREAD

**Issue by amitava82** [trustworktech/create-react-ssr-app#14]
Is it possible to customize webpack config? I'm using code splitting using `react-loadable` and it require a ReactLoadablePlugin added to webpack.

**Comment by maxparelius** [comment]
@amitava82 I follow the philosophy of create-react-app to a 'T'. So if you want to customize webpack you will have to eject by running `npm run eject` in the project. Note that this is irreversible if you do so. It will drop the webpack configs into your project when you eject and you will be able to manage all configs how you like. If you would like to propose adding that plugin to the core I am open to hear why.

**Comment by amitava82** [comment]
Perhaps you could implement something like razzle with a config file? For now, I'm going to eject for my need. Thanks!

**Comment by amitava82** [comment]
But I think we need an example setup that does code splitting and SSR which is very essential. It adds benefit of page load time.  If that needs adding a plugin to core then it should be done. I've been testing few of these code splitting modules however, most of them do not handle css chunks properly forcing us to load all the css imports in once file. Trying out `react-universal-component` which seems to work as expected. I'll continue investigating.

**Comment by appmaker10101** [comment]
Seconded - great project and so easy to use / works well for production, but I'd love to get compression on the build output and this is where some Webpack control would be nice.
