### ISSUE TITLE
Template doesn't run

### ISSUE THREAD

**Issue by AndyBraham** [trustworktech/create-react-ssr-app#15]
I created a new application using ` npx create-react-ssr-app my-app`. When attempting to run the application I recievce the error 'Error parsing app.html'.

**Comment by maxparelius** [comment]
@AndyBraham try refreshing the browser, I have noticed this happens on the first load sometimes, I will look into fixing.

**Comment by maxparelius** [comment]
@AndyBraham this is fixed in the latest update.
