### ISSUE TITLE
Deployment to server

### ISSUE THREAD

**Issue by prashant4dev** [trustworktech/create-react-ssr-app#4]
How could i deploy it to surge or node server?Trying to deploy it in firebase but it didn't work out

**Comment by maxparelius** [comment]
@Prashant-Mutnale since this is a server-side rendered app you can host on any platform that supports node. I believe firebase and surge support static websites only so those tools will not work. If you are looking for a simple solution I recommend Heroku. I can add some documentation on deploying to Heroku. I will let you know when that is done.

**Comment by prashant4dev** [comment]
Thanks @maxparelius for the response, sure i will try to deploy it in Heroku.
It would be great if you could provide us with the documentation, i will wait for it

**Comment by maxparelius** [comment]
@Prashant-Mutnale I have a deployment documentation section here and has information about deploying to heroku: https://trustworktech.github.io/create-react-ssr-app/docs/deployment

**Comment by prashant4dev** [comment]
Thanks @maxparelius for the documentation I did deploy it to heroku but i'm facing some issue with the http i guess i have attached the image below





<img width="1440" alt="Screenshot 2019-03-26 at 12 05 42 AM" src="https://user-images.githubusercontent.com/21354267/54945292-7ed4bc00-4f5b-11e9-882e-98e03771a47e.png">

**Comment by maxparelius** [comment]
@Prashant-Mutnale unable to see the screen shot

**Comment by maxparelius** [comment]
@Prashant-Mutnale can I see what your Procfile looks like?

**Comment by prashant4dev** [comment]
@maxparelius i don't have any Procfile in my root directory.
Do i need to create it ?

i even tried to deploy  the create-react-ssr-app without anychanges but still its showing the same error for it
I have attached the image

<img width="1437" alt="Screenshot 2019-03-26 at 12 57 24 AM" src="https://user-images.githubusercontent.com/21354267/54948254-310f8200-4f62-11e9-821c-930d84bb0cbe.png">

**Comment by maxparelius** [comment]
@Prashant-Mutnale I would create a file called `Procfile` in your root dir and add the following:
```
web: node build
```
You will also need to build the app during heroku deployments so would add an npm script like so to build the app: `"heroku-postbuild": "yarn build"`

**Comment by prashant4dev** [comment]
Thanks @maxparelius  I followed the steps by adding Procfile and adding script to the package.json
The build successfully gets deployed but when i open the link in the browser i'm getting this page

<img width="1439" alt="Screenshot 2019-03-26 at 10 00 41 PM" src="https://user-images.githubusercontent.com/21354267/55015362-af2b6180-5012-11e9-955e-adb2a706ded4.png">

So when i check it by running the  heroku logs --tail it shows the error as  **Error: Cannot find module '/app/build'**

<img width="1059" alt="Screenshot 2019-03-26 at 9 58 54 PM" src="https://user-images.githubusercontent.com/21354267/55015489-ef8adf80-5012-11e9-926c-d16431c128ef.png">

my Procfile consists as 
web: node build

 and package.json as 

{
  "name": "tagmetoo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "bootstrap": "^4.3.1",
    "express": "^4.16.4",
    "firebase": "^5.9.1",
    "react": "^16.8.5",
    "react-bootstrap": "^1.0.0-beta.6",
    "react-dom": "^16.8.5",
    "react-redux": "^6.0.1",
    "react-router-dom": "^5.0.0",
    "react-ssr-scripts": "1.0.4",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-promise": "^0.6.0",
    "redux-thunk": "^2.3.0",
    "serialize-javascript": "^1.6.1"
  },
  "scripts": {
    "start": "react-ssr-scripts start",
    "build": "react-ssr-scripts build",
    "test": "react-ssr-scripts test",
    "eject": "react-ssr-scripts eject",
    "heroku-postbuild": "npm build"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}

**Comment by maxparelius** [comment]
@Prashant-Mutnale Sorry for the delay. I investigated and saw I had a bug in the package. Thanks for patience. Go ahead and update react-ssr-scripts with `yarn add react-ssr-scripts` to get the fix. You can remove the `heroku-postbuild` script which is not needed. Keep the Procfile how you have it and then try and deploy again.

**Comment by maxparelius** [comment]
I verified its working on my end.

**Comment by maxparelius** [comment]
@Prashant-Mutnale were you able to get it working? Can I close?

**Comment by prashant4dev** [comment]
Yes @maxparelius we can close it now its working fine.
