### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by nicolasmn** [trustworktech/create-react-ssr-app#8]
### Is this a bug report?

Yes

### Did you try recovering your dependencies?

Yes

### Which terms did you search for in User Guide?

CORS

### Environment

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
  Binaries:
    Node: 8.10.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 65.0.1
    Safari: 12.1.1
  npmPackages:
    escape-string-regexp: ^2.0.0 => 2.0.0 (1.0.5, 1.0.5)
    express: ^4.17.1 => 4.17.1 
    react: ^16.8.6 => 16.8.6 
    react-dom: ^16.8.6 => 16.8.6 
    react-ssr-scripts: 2.1.3 => 2.1.3 
  npmGlobalPackages:
    create-react-ssr-app: Not Found

### Steps to Reproduce

1. Create a new app using `npx create-react-ssr-app`
2. Try to link to any local font file from a CSS file (and also make sure to use that font)
3. Get the CORS error

### Expected Behavior

Font loads without CORS error

### Actual Behavior

Font doesn't load. Instead I get a CORS error:
![cors](https://user-images.githubusercontent.com/855244/60882779-e1bb3c00-a248-11e9-81fe-a3a7f458f1ea.png)

**Comment by maxparelius** [comment]
@nicolasmn try adding `cors` package: `yarn add cors` and then add the middleware to your node server: `app.use(cors())`

**Comment by nicolasmn** [comment]
I actually did try that already, without luck. Seems that the problem is with the other server (port 3030), not the one from `./src/server` (port 3000)

**Comment by maxparelius** [comment]
@nicolasmn can I see a snippet of your css file showing how you import the font file?

**Comment by nicolasmn** [comment]
@maxparelius with the font files placed in `./src/client/fonts/` and my CSS file in `./src/client/index.css` I'm currently importing the fonts like this (but tried it without the leading dot and without leading slash as well):
```css
@font-face {
  font-family: "Example Font";
  font-weight: normal;
  font-display: swap;
  src: url('./fonts/ExampleFont.woff2'),
       url('./fonts/ExampleFont.woff');
}
```

**Comment by maxparelius** [comment]
@nicolasmn this should be fixed if you update `react-ssr-scripts`

**Comment by nicolasmn** [comment]
Yes! It works, thank you very much!
