### ISSUE TITLE
Build Error: Cannot find module ‘./utils/verifyTypeScriptSetup’

### ISSUE THREAD

**Issue by nicolasmn** [trustworktech/create-react-ssr-app#9]
### Is this a bug report?

Yes

### Did you try recovering your dependencies?

Yes

### Environment

System:
   OS: Linux 3.10 Debian GNU/Linux 9 (stretch) 9 (stretch)
   CPU: (40) x64 Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz
 Binaries:
   Node: 10.16.0 - /usr/local/bin/node
   Yarn: 1.16.0 - /usr/local/bin/yarn
   npm: 6.9.0 - /usr/local/bin/npm
 Browsers:
   Chrome: Not Found
   Firefox: Not Found
 npmPackages:
   escape-string-regexp: ^2.0.0 => 2.0.0 (1.0.5, 1.0.5)
   express: ^4.17.1 => 4.17.1
   react: ^16.8.6 => 16.8.6
   react-dom: ^16.8.6 => 16.8.6
   react-ssr-scripts: 2.1.3 => 2.1.3
 npmGlobalPackages:
   create-react-ssr-app: Not Found

### Steps to Reproduce

1. Use a Linux distribution
2. Try to build a previously created project using `npm run build` 

### Expected Behavior

Build finishes without errors

### Actual Behavior

Build failed with error:
![build-error](https://user-images.githubusercontent.com/855244/60963370-e1867380-a310-11e9-8b9a-d73128487134.png)

**Comment by maxparelius** [comment]
@nicolasmn can you try and update the `react-ssr-scrips` package? `yarn add react-ssr-scripts`

**Comment by sh4hids** [comment]
@maxparelius Facing the same problem when try to run `npx create-react-ssr-app my-app` from my linux machine. I have node 12.5.0 installed. Also tried with yarn, but no luck.

Output:
```bash
npx create-react-ssr-app my-app
npx: installed 65 in 9.12s

Creating a new React SSR app in /media/sim/DevHouse/lab/my-app.

Installing packages. This might take a couple of minutes.
Installing express, react, react-dom, and react-ssr-scripts...


> core-js-pure@3.1.4 postinstall /media/sim/DevHouse/lab/my-app/node_modules/core-js-pure
> node scripts/postinstall || echo "ignore"

+ express@4.17.1
+ react-dom@16.8.6
+ react@16.8.6
+ react-ssr-scripts@2.1.3
+ escape-string-regexp@2.0.0
added 1371 packages from 723 contributors and audited 902220 packages in 82.435s
found 0 vulnerabilities

internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module './utils/verifyTypeScriptSetup'
Require stack:
- /media/sim/DevHouse/lab/my-app/node_modules/react-ssr-scripts/scripts/init.js
- /media/sim/DevHouse/lab/my-app/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/media/sim/DevHouse/lab/my-app/node_modules/react-ssr-scripts/scripts/init.js:24:31)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/media/sim/DevHouse/lab/my-app/node_modules/react-ssr-scripts/scripts/init.js',
    '/media/sim/DevHouse/lab/my-app/[eval]'
  ]
}

Aborting installation.
  node  has failed.

Deleting generated file... node_modules
Deleting generated file... package.json
Done.

```

**Comment by nicolasmn** [comment]
@maxparelius reinstalling the package didn't help

**Comment by maxparelius** [comment]
@nicolasmn @sh4hids try removing `create-react-ssr-app` and installing again with `npm uninstall -g create-react-ssr-app` and then `npx create-react-ssr-app my-app`

**Comment by sh4hids** [comment]
@maxparelius Tried removing and installing again, but same problem remains.

**Comment by nicolasmn** [comment]
Same here, updated `react-ssr-scripts` to 2.1.4 and the error keeps happening

**Comment by sh4hids** [comment]
@maxparelius  I believe I found the issue:
[Here](https://github.com/trustworktech/create-react-ssr-app/blob/5acd28db4e3098c16d7055844a47c553b6324cba/packages/react-ssr-scripts/scripts/init.js#L24) you are importing `verifyTypeScriptSetup` from `'./utils/verifyTypeScriptSetup'` (`s` of script is Capital).  But the actual file name is [verifyTypescriptSetup.js](https://github.com/trustworktech/create-react-ssr-app/blob/master/packages/react-ssr-scripts/scripts/utils/verifyTypescriptSetup.js) (`s` of script is small).

I Hope, we are getting a fix soon...

**Comment by SanKlein** [comment]
@maxparelius Hey Max, will you please approve my PR for the fix above, or make the fix specified in the comment above? Thank you!

**Comment by maxparelius** [comment]
@nicolasmn @sh4hids @SanKlein Thanks for the help guys sorry for delays been on vacation. The issue is fixed and published.
